### PR TITLE
update to latest hxPixels...

### PR DESCRIPTION
**Pull request by azrafe7**
to address some openfl internal classes being moved around

### CODE REVIEW

**Comment by nanjizal** [comment]
Think you have you have used tab spacing, and I think I have gone with 4 spaces accross hxDaedalus in source code or was my intention? 
Harder for us to track changes in future as the diff files seem to not show relevant differences properly?

Was thinking maybe worth removing Luxe and Flambe, what do you think ? 

Locally I still have them both in my haxelib, but no one is using them?  I was thinking to add depreciations to thier example repos.
 
I suspect Ceramic maybe similar to Luxe just had a quick look but not tested...

https://github.com/ceramic-engine/clay/blob/main/src/clay/buffers/Uint8Array.hx
https://github.com/ceramic-engine/ceramic/blob/master/runtime/src/ceramic/Texture.hx

Guessing swapping Luxe for Ceramic it's something like?
```Haxe
  @:from static public function fromCeramicTexture( texture: ceramic.Texture ): Pixels {
    var pixels = new Pixels( texture.width, texture.height, false );
    pixels.format = PixelFormat.RGBA;

    var data = new ceramic.Uint8Array( texture.width * texture.height * 4 );
    texture.fetchPixels(data);
    pixels.bytes = data.toBytes();

    return pixels;
  }

  @:from static public function fromCeramicAssetImage( assetImage: ceramic.AssetImage ): Pixels {
      return fromCeramicTexture( assetImage.texture );
  }

  public function applyToCeramicTexture(texture:ceramic.Texture) {
   // nativeWidthActual??
    var data = Bytes.alloc(texture.nativeWidth * texture.nativeHeight * 4);

    var padded_width = texture.nativeWidth;
    var stride = this.width * 4;

    for (y in 0...this.height) {
      data.blit(y * padded_width * 4, this.bytes, y * stride, stride);
    }

    texture.submitPixels(ceramic.Uint8Array.fromBytes(data));  // rebind texture
  }
```


It would be nice to add some support for Kha and Heaps, not sure if ideal taken implementation approach from the hxDaedalus demos I made.

```Haxe
@:from
inline static function fromKha( img: kha.Image ): Pixels {
    var pixels = new Pixels( img.height, img.width, true );
    for( y in 0...img.height )for( x in 0...img.width ) pixels.setPixel( x, y, img.at( x, y ) );
    return pixels;
}
```

```Haxe
@:from
inline static function fromHeaps( img: hxd.res.Image ): Pixel {
    return hxPixels.Pixels.fromBytes( img.bytes, img.width, img.height );
}
```

**Comment by nanjizal** [comment]
oh by the way thanks for sorting this out.  Let me know if worth adding additions, and removing old, and if we can go with spacing rather than tabs many thanks.

**Comment by nanjizal** [comment]
Would be nice to add Gluon support??? but not sure where to start.

**Comment by nanjizal** [comment]
if the kha, heaps and ceramic mods seem suitable I can do a pull on hxPixels direct as well.  Have you looked into integration testing?? I am not too sure on it.

**Comment by azrafe7** [comment]
I've updated the PR so that the file is using the same white space as the previous one (now the diff is cleaner).
Will still need another commit after being merged, to conform to tab/spaces of the other files.

Waiting for your PR for hxPixels working on Kha/Heaps/Ceramic. :wink:

**Pull request merged**
